In [1]:
import pandas as pd
import numpy as np
import re

import nltk

from nltk.corpus import stopwords

from sklearn.model_selection import train_test_split

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1787761784.533974  139990 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1787761784.629396  139990 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1787761786.668764  139990 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

In [2]:
nltk.download("stopwords")

/home/aximsoft/snap/code/258/.local/share/virtualenvs/Text_Sentiment_Analysis-D79r_KZq/lib/python3.13/site-packages/nltk/downloader.py:1076: UserWarning: NLTK will not authorize the non-private download directory '/home/aximsoft/nltk_data': it (or an ancestor) is world- or group-writable, so another local user could plant files there. Choose a private location such as ~/nltk_data.
  for msg in self.incr_download(info_or_id, download_dir, force):
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/aximsoft/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
df = pd.read_csv("../Dataset/IMDB Dataset.csv")

In [4]:
df.shape

(50000, 2)

In [5]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [6]:
print(df.isnull().sum())

review       0
sentiment    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(418)

In [8]:
df = df.drop_duplicates().reset_index(drop=True)

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.shape

(49582, 2)

# Encode

In [11]:
sentiment_mapping = {
    "negative": 0,
    "positive": 1
}

df["sentiment_label"] = df["sentiment"].map(sentiment_mapping)

df[["sentiment", "sentiment_label"]].head()

  sentiment  sentiment_label
0  positive                1
1  positive                1
2  positive                1
3  negative                0
4  positive                1

In [12]:
print(df["sentiment_label"].value_counts())

sentiment_label
1    24884
0    24698
Name: count, dtype: int64

# Create the Text Cleaning Function

In [13]:
# NEGATION_WORDS = {
#     "no",
#     "not",
#     "nor",
#     "never",
#     "neither",
#     "none",
#     "nobody",
#     "nothing",
#     "nowhere",
#     "hardly",
#     "scarcely",
#     "barely",
#     "isn't",
#     "wasn't",
#     "didn't",
#     "don't",
#     "can't",
#     "couldn't",
#     "won't"
# }

stop_words = set(stopwords.words("english"))

# stop_words = stop_words - NEGATION_WORDS

def clean_text(text):

    text = text.lower()

    text = re.sub(r"<.*?>", " ", text)

    text = re.sub(r"[^a-zA-Z\s]", " ", text)

    text = re.sub(r"\s+", " ", text).strip()

    words = text.split()

    words = [
        word
        for word in words
        if word not in stop_words
    ]

    return " ".join(words)

# test the clean function

In [14]:
sample_review = df.loc[0, "review"]

print("Original review:\n")
print(sample_review)

print("\n" + "=" * 80)

cleaned_review = clean_text(sample_review)

print("Cleaned review:\n")
print(cleaned_review)

Original review:

One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.

================================================================================
Cleaned review:

one reviewers mentioned watching oz episode hooked right exactly happened first thing struck oz brutality unflinching scenes violence set right word go trust show faint hearted timid show pulls punches regards drugs sex violence hardcore classic use word called oz nickname given oswald maximum security state penitentary focuses mainly emerald city experimental section prison cells glass fronts face inwards privacy high agenda em city home many aryans muslims gangstas latinos christians italians irish scuffles death stares dodgy dealings shady agreements never far away would say main appeal show due fact goes shows dare forget pretty pictures painted mainstream audiences forget charm forget romance oz mess around first episode ever saw struck nasty surreal say ready watched developed taste oz got accustomed high levels graphic violence violence injustice crooked guards sold nickel inmates kill order get away well mannered middle class inmates turned prison bitches due lack street skills prison experience watching oz may become comfortable uncomfortable viewing thats get touch darker side

In [15]:
# Apply Cleaning to the Complete Dataset

df["cleaned_review"] = df["review"].apply(clean_text)

In [16]:
df[["review", "cleaned_review", "sentiment"]].head()

,review,cleaned_review,sentiment
0,One of the other reviewers has mentioned that ...,one reviewers mentioned watching oz episode ho...,positive
1,A wonderful little production. <br /><br />The...,wonderful little production filming technique ...,positive
2,I thought this was a wonderful way to spend ti...,thought wonderful way spend time hot summer we...,positive
3,Basically there's a family where a little boy ...,basically family little boy jake thinks zombie...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",petter mattei love time money visually stunnin...,positive

# Check for Empty Reviews

In [17]:
empty_reviews = (df["cleaned_review"].str.strip() == "").sum()

print("Empty reviews after preprocessing:", empty_reviews)

Empty reviews after preprocessing: 0

In [18]:
df.shape

(49582, 4)

In [19]:
df.head()

,review,sentiment,sentiment_label,cleaned_review
0,One of the other reviewers has mentioned that ...,positive,1,one reviewers mentioned watching oz episode ho...
1,A wonderful little production. <br /><br />The...,positive,1,wonderful little production filming technique ...
2,I thought this was a wonderful way to spend ti...,positive,1,thought wonderful way spend time hot summer we...
3,Basically there's a family where a little boy ...,negative,0,basically family little boy jake thinks zombie...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,1,petter mattei love time money visually stunnin...

# Input and output

In [20]:
X = df["cleaned_review"]

y = df["sentiment_label"]

In [21]:
print("Number of reviews:", len(X))
print("Number of labels:", len(y))

Number of reviews: 49582
Number of labels: 49582

In [22]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.15,
    random_state=42,
    stratify=y
)

In [23]:
X_train, X_val, y_train, y_val = train_test_split(
    X_train,
    y_train,
    test_size=0.1765,
    random_state=42,
    stratify=y_train
)

In [24]:
print("Training samples:", len(X_train))
print("Validation samples:", len(X_val))
print("Testing samples:", len(X_test))

Training samples: 34705
Validation samples: 7439
Testing samples: 7438

# Verify Class Distribution

In [25]:
print("Training distribution:")
print(y_train.value_counts(normalize=True))

print("\nValidation distribution:")
print(y_val.value_counts(normalize=True))

print("\nTest distribution:")
print(y_test.value_counts(normalize=True))

Training distribution:
sentiment_label
1    0.501887
0    0.498113
Name: proportion, dtype: float64

Validation distribution:
sentiment_label
1    0.501815
0    0.498185
Name: proportion, dtype: float64

Test distribution:
sentiment_label
1    0.501882
0    0.498118
Name: proportion, dtype: float64

# Tokenization

In [26]:
tokenizer = Tokenizer(
    num_words=20000,
    oov_token="<OOV>"
)

In [27]:
tokenizer.fit_on_texts(X_train)

In [28]:
# Check vocab   

tokenizer.word_index

{'<OOV>': 1,
 'movie': 2,
 'film': 3,
 'one': 4,
 'like': 5,
 'good': 6,
 'time': 7,
 'even': 8,
 'would': 9,
 'story': 10,
 'really': 11,
 'see': 12,
 'well': 13,
 'much': 14,
 'bad': 15,
 'get': 16,
 'great': 17,
 'people': 18,
 'also': 19,
 'first': 20,
 'made': 21,
 'make': 22,
 'could': 23,
 'way': 24,
 'movies': 25,
 'think': 26,
 'characters': 27,
 'character': 28,
 'watch': 29,
 'films': 30,
 'two': 31,
 'seen': 32,
 'many': 33,
 'love': 34,
 'acting': 35,
 'plot': 36,
 'never': 37,
 'life': 38,
 'best': 39,
 'show': 40,
 'know': 41,
 'little': 42,
 'ever': 43,
 'man': 44,
 'better': 45,
 'end': 46,
 'scene': 47,
 'still': 48,
 'say': 49,
 'scenes': 50,
 'something': 51,
 'go': 52,
 'back': 53,
 'real': 54,
 'thing': 55,
 'watching': 56,
 'actors': 57,
 'years': 58,
 'though': 59,
 'director': 60,
 'funny': 61,
 'another': 62,
 'old': 63,
 'actually': 64,
 'work': 65,
 'makes': 66,
 'nothing': 67,
 'look': 68,
 'going': 69,
 'find': 70,
 'lot': 71,
 'new': 72,
 'every': 73,
 'part': 74,
 'cast': 75,
 'world': 76,
 'things': 77,
 'quite': 78,
 'us': 79,
 'want': 80,
 'horror': 81,
 'pretty': 82,
 'around': 83,
 'seems': 84,
 'however': 85,
 'got': 86,
 'big': 87,
 'enough': 88,
 'take': 89,
 'young': 90,
 'fact': 91,
 'thought': 92,
 'long': 93,
 'may': 94,
 'give': 95,
 'comedy': 96,
 'must': 97,
 'series': 98,
 'action': 99,
 'right': 100,
 'music': 101,
 'original': 102,
 'without': 103,
 'guy': 104,
 'role': 105,
 'saw': 106,
 'come': 107,
 'gets': 108,
 'almost': 109,
 'times': 110,
 'always': 111,
 'point': 112,
 'whole': 113,
 'least': 114,
 'interesting': 115,
 'done': 116,
 'far': 117,
 'bit': 118,
 'script': 119,
 'family': 120,
 'might': 121,
 'making': 122,
 'minutes': 123,
 'feel': 124,
 'anything': 125,
 'since': 126,
 'tv': 127,
 'probably': 128,
 'last': 129,
 'performance': 130,
 'girl': 131,
 'away': 132,
 'yet': 133,
 'kind': 134,
 'rather': 135,
 'fun': 136,
 'anyone': 137,
 'woman': 138,
 'sure': 139,
 'day': 140,
 'played': 141,
 'worst': 142,
 'hard': 143,
 'found': 144,
 'looking': 145,
 'screen': 146,
 'believe': 147,
 'although': 148,
 'trying': 149,
 'especially': 150,
 'book': 151,
 'dvd': 152,
 'put': 153,
 'set': 154,
 'comes': 155,
 'course': 156,
 'goes': 157,
 'three': 158,
 'everything': 159,
 'ending': 160,
 'worth': 161,
 'place': 162,
 'different': 163,
 'maybe': 164,
 'actor': 165,
 'let': 166,
 'main': 167,
 'shows': 168,
 'american': 169,
 'someone': 170,
 'effects': 171,
 'sense': 172,
 'play': 173,
 'reason': 174,
 'true': 175,
 'money': 176,
 'job': 177,
 'watched': 178,
 'everyone': 179,
 'year': 180,
 'together': 181,
 'high': 182,
 'audience': 183,
 'looks': 184,
 'plays': 185,
 'war': 186,
 'instead': 187,
 'special': 188,
 'later': 189,
 'said': 190,
 'john': 191,
 'takes': 192,
 'half': 193,
 'seeing': 194,
 'night': 195,
 'seem': 196,
 'beautiful': 197,
 'version': 198,
 'house': 199,
 'left': 200,
 'wife': 201,
 'black': 202,
 'shot': 203,
 'star': 204,
 'idea': 205,
 'excellent': 206,
 'father': 207,
 'else': 208,
 'fan': 209,
 'mind': 210,
 'death': 211,
 'budget': 212,
 'used': 213,
 'simply': 214,
 'poor': 215,
 'second': 216,
 'nice': 217,
 'read': 218,
 'short': 219,
 'completely': 220,
 'less': 221,
 'top': 222,
 'home': 223,
 'along': 224,
 'men': 225,
 'dead': 226,
 'line': 227,
 'production': 228,
 'boring': 229,
 'camera': 230,
 'hollywood': 231,
 'enjoy': 232,
 'need': 233,
 'help': 234,
 'either': 235,
 'kids': 236,
 'try': 237,
 'women': 238,
 'given': 239,
 'classic': 240,
 'full': 241,
 'friends': 242,
 'next': 243,
 'wrong': 244,
 'school': 245,
 'rest': 246,
 'use': 247,
 'low': 248,
 'truly': 249,
 'stupid': 250,
 'video': 251,
 'start': 252,
 'awful': 253,
 'performances': 254,
 'couple': 255,
 'sex': 256,
 'tell': 257,
 'understand': 258,
 'came': 259,
 'mean': 260,
 'recommend': 261,
 'getting': 262,
 'remember': 263,
 'terrible': 264,
 'perhaps': 265,
 'keep': 266,
 'mother': 267,
 'face': 268,
 'style': 269,
 'name': 270,
 'moments': 271,
 'person': 272,
 'human': 273,
 'episode': 274,
 'wonderful': 275,
 'often': 276,
 'written': 277,
 'others': 278,
 'boy': 279,
 'playing': 280,
 'perfect': 281,
 'piece': 282,
 'definitely': 283,
 'children': 284,
 'head': 285,
 'stars': 286,
 'gives': 287,
 'small': 288,
 'early': 289,
 'dialogue': 290,
 'lines': 291,
 'lost': 292,
 'oh': 293,
 'finally': 294,
 'went': 295,
 'entertaining': 296,
 'sort': 297,
 'absolutely': 298,
 'yes': 299,
 'live': 300,
 'title': 301,
 'case': 302,
 'certainly': 303,
 'cinema': 304,
 'guys': 305,
 'liked': 306,
 'picture': 307,
 'worse': 308,
 'laugh': 309,
 'friend': 310,
 'hope': 311,
 'several': 312,
 'loved': 313,
 'become': 314,
 'felt': 315,
 'called': 316,
 'white': 317,
 'supposed': 318,
 'mr': 319,
 'drama': 320,
 'entire': 321,
 'based': 322,
 'sound': 323,
 'fans': 324,
 'game': 325,
 'totally': 326,
 'problem': 327,
 'overall': 328,
 'dark': 329,
 'beginning': 330,
 'care': 331,
 'waste': 332,
 'guess': 333,
 'b': 334,
 'evil': 335,
 'despite': 336,
 'example': 337,
 'lead': 338,
 'throughout': 339,
 'turn': 340,
 'able': 341,
 'becomes': 342,
 'seemed': 343,
 'final': 344,
 'humor': 345,
 'lives': 346,
 'wanted': 347,
 'direction': 348,
 'unfortunately': 349,
 'quality': 350,
 'history': 351,
 'already': 352,
 'days': 353,
 'killer': 354,
 'flick': 355,
 'michael': 356,
 'art': 357,
 'amazing': 358,
 'run': 359,
 'son': 360,
 'fine': 361,
 'wants': 362,
 'heart': 363,
 'writing': 364,
 'behind': 365,
 'child': 366,
 'close': 367,
 'etc': 368,
 'side': 369,
 'horrible': 370,
 'works': 371,
 'genre': 372,
 'girls': 373,
 'god': 374,
 'kill': 375,
 'turns': 376,
 'today': 377,
 'past': 378,
 'act': 379,
 'gave': 380,
 'eyes': 381,
 'directed': 382,
 'hour': 383,
 'matter': 384,
 'stuff': 385,
 'parts': 386,
 'car': 387,
 'late': 388,
 'viewer': 389,
 'hand': 390,
 'enjoyed': 391,
 'decent': 392,
 'kid': 393,
 'obviously': 394,
 'brilliant': 395,
 'sometimes': 396,
 'tries': 397,
 'soon': 398,
 'expect': 399,
 'town': 400,
 'city': 401,
 'killed': 402,
 'favorite': 403,
 'type': 404,
 'starts': 405,
 'stop': 406,
 'actress': 407,
 'blood': 408,
 'highly': 409,
 'thinking': 410,
 'says': 411,
 'self': 412,
 'feeling': 413,
 'known': 414,
 'group': 415,
 'voice': 416,
 'daughter': 417,
 'writer': 418,
 'anyway': 419,
 'took': 420,
 'happens': 421,
 'experience': 422,
 'fight': 423,
 'heard': 424,
 'hero': 425,
 'moment': 426,
 'leave': 427,
 'strong': 428,
 'coming': 429,
 'except': 430,
 'slow': 431,
 'hit': 432,
 'roles': 433,
 'told': 434,
 'score': 435,
 'brother': 436,
 'stories': 437,
 'save': 438,
 'song': 439,
 'including': 440,
 'hell': 441,
 'violence': 442,
 'happen': 443,
 'hilarious': 444,
 'particularly': 445,
 'crap': 446,
 'chance': 447,
 'looked': 448,
 'cannot': 449,
 'serious': 450,
 'murder': 451,
 'involved': 452,
 'ok': 453,
 'alone': 454,
 'lack': 455,
 'simple': 456,
 'extremely': 457,
 'david': 458,
 'police': 459,
 'cut': 460,
 'cool': 461,
 'taken': 462,
 'seriously': 463,
 'ago': 464,
 'obvious': 465,
 'wonder': 466,
 'complete': 467,
 'husband': 468,
 'gore': 469,
 'attempt': 470,
 'please': 471,
 'james': 472,
 'robert': 473,
 'exactly': 474,
 'across': 475,
 'living': 476,
 'released': 477,
 'shown': 478,
 'happened': 479,
 'age': 480,
 'none': 481,
 'opening': 482,
 'interest': 483,
 'english': 484,
 'number': 485,
 'jokes': 486,
 'saying': 487,
 'reality': 488,
 'cinematography': 489,
 'whose': 490,
 'relationship': 491,
 'hours': 492,
 'talent': 493,
 'order': 494,
 'running': 495,
 'usually': 496,
 'change': 497,
 'career': 498,
 'shots': 499,
 'country': 500,
 'sad': 501,
 'word': 502,
 'huge': 503,
 'view': 504,
 'possible': 505,
 'novel': 506,
 'four': 507,
 'silly': 508,
 'ridiculous': 509,
 'annoying': 510,
 'power': 511,
 'level': 512,
 'words': 513,
 'light': 514,
 'ends': 515,
 'important': 516,
 'attention': 517,
 'female': 518,
 'taking': 519,
 'wish': 520,
 'mostly': 521,
 'beyond': 522,
 'body': 523,
 'jack': 524,
 'turned': 525,
 'talking': 526,
 'usual': 527,
 'musical': 528,
 'room': 529,
 'middle': 530,
 'documentary': 531,
 'ones': 532,
 'somewhat': 533,
 'call': 534,
 'basically': 535,
 'strange': 536,
 'started': 537,
 'scary': 538,
 'knows': 539,
 'modern': 540,
 'major': 541,
 'happy': 542,
 'clich': 543,
 'apparently': 544,
 'rating': 545,
 'knew': 546,
 'episodes': 547,
 'team': 548,
 'single': 549,
 'king': 550,
 'television': 551,
 'due': 552,
 'non': 553,
 'upon': 554,
 'opinion': 555,
 'french': 556,
 'disappointed': 557,
 'events': 558,
 'finds': 559,
 'cheap': 560,
 'miss': 561,
 'earth': 562,
 'problems': 563,
 'local': 564,
 'enjoyable': 565,
 'five': 566,
 'british': 567,
 'straight': 568,
 'songs': 569,
 'clearly': 570,
 'thriller': 571,
 'easily': 572,
 'comic': 573,
 'future': 574,
 'similar': 575,
 'talk': 576,
 'eye': 577,
 'add': 578,
 'moving': 579,
 'space': 580,
 'predictable': 581,
 'class': 582,
 'sequence': 583,
 'die': 584,
 'review': 585,
 'near': 586,
 'tells': 587,
 'filmed': 588,
 'george': 589,
 'sets': 590,
 'ten': 591,
 'fast': 592,
 'soundtrack': 593,
 'e': 594,
 'falls': 595,
 'lots': 596,
 'entertainment': 597,
 'message': 598,
 'bring': 599,
 'appears': 600,
 'sister': 601,
 'whether': 602,
 'surprised': 603,
 'parents': 604,
 'hate': 605,
 'supporting': 606,
 'release': 607,
 'suspense': 608,
 'bunch': 609,
 'sequel': 610,
 'clear': 611,
 'dialog': 612,
 'romantic': 613,
 'certain': 614,
 'rock': 615,
 'giving': 616,
 'within': 617,
 'theme': 618,
 'theater': 619,
 'mention': 620,
 'using': 621,
 'buy': 622,
 'tale': 623,
 'needs': 624,
 'dull': 625,
 'easy': 626,
 'showing': 627,
 'working': 628,
 'ways': 629,
 'oscar': 630,
 'sorry': 631,
 'named': 632,
 'effort': 633,
 'monster': 634,
 'dog': 635,
 'among': 636,
 'stand': 637,
 'check': 638,
 'mystery': 639,
 'minute': 640,
 'nearly': 641,
 'greatest': 642,
 'fall': 643,
 'storyline': 644,
 'th': 645,
 'typical': 646,
 'stay': 647,
 'richard': 648,
 'doubt': 649,
 'gone': 650,
 'feels': 651,
 'subject': 652,
 'feature': 653,
 'dr': 654,
 'lady': 655,
 'red': 656,
 'avoid': 657,
 'actual': 658,
 'comments': 659,
 'general': 660,
 'move': 661,
 'famous': 662,
 'tried': 663,
 'fantastic': 664,
 'editing': 665,
 'deal': 666,
 'material': 667,
 'crime': 668,
 'realistic': 669,
 'follow': 670,
 'form': 671,
 'points': 672,
 'killing': 673,
 'rent': 674,
 'elements': 675,
 'tom': 676,
 'kept': 677,
 'viewing': 678,
 'period': 679,
 'viewers': 680,
 'okay': 681,
 'somehow': 682,
 'imagine': 683,
 'means': 684,
 'paul': 685,
 'leads': 686,
 'peter': 687,
 'premise': 688,
 'animation': 689,
 'brought': 690,
 'weak': 691,
 'believable': 692,
 'surprise': 693,
 'deep': 694,
 'figure': 695,
 'expected': 696,
 'imdb': 697,
 'crew': 698,
 'begins': 699,
 'average': 700,
 'hear': 701,
 'learn': 702,
 'dance': 703,
 'difficult': 704,
 'particular': 705,
 'wait': 706,
 'atmosphere': 707,
 'indeed': 708,
 'boys': 709,
 'open': 710,
 'situation': 711,
 'sit': 712,
 'doctor': 713,
 'eventually': 714,
 'free': 715,
 'romance': 716,
 'lame': 717,
 'sequences': 718,
 'shame': 719,
 'reviews': 720,
 'poorly': 721,
 'america': 722,
 'forget': 723,
 'decided': 724,
 'york': 725,
 'hot': 726,
 'note': 727,
 'whatever': 728,
 'fi': 729,
 'reading': 730,
 'sexual': 731,
 'sci': 732,
 'cop': 733,
 'truth': 734,
 'unless': 735,
 'society': 736,
 'meet': 737,
 'footage': 738,
 'de': 739,
 'write': 740,
 'third': 741,
 'box': 742,
 'cheesy': 743,
 'lee': 744,
 'leaves': 745,
 'perfectly': 746,
 'superb': 747,
 'credits': 748,
 'needed': 749,
 'meets': 750,
 'forced': 751,
 'beauty': 752,
 'gay': 753,
 'memorable': 754,
 'emotional': 755,
 'effect': 756,
 'became': 757,
 'begin': 758,
 'japanese': 759,
 'male': 760,
 'acted': 761,
 'features': 762,
 'stage': 763,
 'hands': 764,
 'laughs': 765,
 'nature': 766,
 'personal': 767,
 'otherwise': 768,
 'result': 769,
 'street': 770,
 'previous': 771,
 'joe': 772,
 'girlfriend': 773,
 'interested': 774,
 'season': 775,
 'sounds': 776,
 'comment': 777,
 'writers': 778,
 'air': 779,
 'question': 780,
 'possibly': 781,
 'screenplay': 782,
 'western': 783,
 'crazy': 784,
 'weird': 785,
 'inside': 786,
 'total': 787,
 'pay': 788,
 'earlier': 789,
 'mess': 790,
 'plus': 791,
 'quickly': 792,
 'c': 793,
 'badly': 794,
 'background': 795,
 'island': 796,
 'battle': 797,
 'setting': 798,
 'forward': 799,
 'following': 800,
 'development': 801,
 'fire': 802,
 'towards': 803,
 'front': 804,
 'directors': 805,
 'masterpiece': 806,
 'powerful': 807,
 'baby': 808,
 'keeps': 809,
 'worked': 810,
 'dumb': 811,
 'brings': 812,
 'creepy': 813,
 'business': 814,
 'copy': 815,
 'apart': 816,
 'ask': 817,
 'dramatic': 818,
 'match': 819,
 'william': 820,
 'directing': 821,
 'mark': 822,
 'zombie': 823,
 'dream': 824,
 'rate': 825,
 'bill': 826,
 'incredibly': 827,
 'admit': 828,
 'unique': 829,
 'rich': 830,
 'disney': 831,
 'appear': 832,
 'fighting': 833,
 'various': 834,
 'present': 835,
 'plenty': 836,
 'fails': 837,
 'water': 838,
 'fairly': 839,
 'leading': 840,
 'meant': 841,
 'political': 842,
 'caught': 843,
 'portrayed': 844,
 'reasons': 845,
 'joke': 846,
 'party': 847,
 'spent': 848,
 'telling': 849,
 'talented': 850,
 'era': 851,
 'realize': 852,
 'success': 853,
 'ideas': 854,
 'cover': 855,
 'twist': 856,
 'older': 857,
 'create': 858,
 'unlike': 859,
 'deserves': 860,
 'wasted': 861,
 'villain': 862,
 'break': 863,
 'odd': 864,
 'expecting': 865,
 'list': 866,
 'attempts': 867,
 'fantasy': 868,
 'cute': 869,
 'plain': 870,
 'clever': 871,
 'large': 872,
 'manages': 873,
 'co': 874,
 'ended': 875,
 'office': 876,
 'gun': 877,
 'escape': 878,
 'outside': 879,
 'casting': 880,
 'van': 881,
 'missed': 882,
 'flat': 883,
 'members': 884,
 'spoilers': 885,
 'hardly': 886,
 'century': 887,
 'return': 888,
 'agree': 889,
 'created': 890,
 'familiar': 891,
 'laughing': 892,
 'public': 893,
 'secret': 894,
 'recently': 895,
 'waiting': 896,
 'married': 897,
 'filmmakers': 898,
 'scott': 899,
 'company': 900,
 'missing': 901,
 'wrote': 902,
 'italian': 903,
 'pace': 904,
 'nudity': 905,
 'potential': 906,
 'remake': 907,
 'store': 908,
 'visual': 909,
 'incredible': 910,
 'train': 911,
 'science': 912,
 'german': 913,
 'considering': 914,
 'cause': 915,
 'pure': 916,
 'uses': 917,
 'filled': 918,
 'produced': 919,
 'cold': 920,
 'speak': 921,
 'state': 922,
 'suddenly': 923,
 'popular': 924,
 'mentioned': 925,
 'hair': 926,
 'hold': 927,
 'sadly': 928,
 'trouble': 929,
 'slightly': 930,
 'died': 931,
 'convincing': 932,
 'cartoon': 933,
 'anti': 934,
 'credit': 935,
 'brain': 936,
 'intelligent': 937,
 'sees': 938,
 'mad': 939,
 'sweet': 940,
 'former': 941,
 'language': 942,
 'value': 943,
 'tension': 944,
 'force': 945,
 'portrayal': 946,
 'kills': 947,
 'bored': 948,
 'la': 949,
 'decides': 950,
 'choice': 951,
 'dancing': 952,
 'moves': 953,
 'amount': 954,
 'f': 955,
 'band': 956,
 'amusing': 957,
 'g': 958,
 'pointless': 959,
 'alive': 960,
 'violent': 961,
 'fit': 962,
 'control': 963,
 'situations': 964,
 'neither': 965,
 'yeah': 966,
 'road': 967,
 'u': 968,
 'recommended': 969,
 'compared': 970,
 'fear': 971,
 'gang': 972,
 'respect': 973,
 'brothers': 974,
 'fiction': 975,
 'drug': 976,
 'project': 977,
 'biggest': 978,
 'meaning': 979,
 'master': 980,
 'studio': 981,
 'christmas': 982,
 'follows': 983,
 'images': 984,
 'common': 985,
 'jane': 986,
 'vampire': 987,
 'spirit': 988,
 'entirely': 989,
 'social': 990,
 'fake': 991,
 'successful': 992,
 'concept': 993,
 'law': 994,
 'depth': 995,
 'effective': 996,
 'focus': 997,
 'longer': 998,
 'sick': 999,
 'runs': 1000,
 ...}

In [29]:
word_index = tokenizer.word_index

print("Total vocabulary:", len(word_index))

Total vocabulary: 85869

In [30]:
list(word_index.items())[:20]

[('<OOV>', 1),
 ('movie', 2),
 ('film', 3),
 ('one', 4),
 ('like', 5),
 ('good', 6),
 ('time', 7),
 ('even', 8),
 ('would', 9),
 ('story', 10),
 ('really', 11),
 ('see', 12),
 ('well', 13),
 ('much', 14),
 ('bad', 15),
 ('get', 16),
 ('great', 17),
 ('people', 18),
 ('also', 19),
 ('first', 20)]

In [31]:
# Training:

X_train_sequences = tokenizer.texts_to_sequences(X_train)

# `Validation:

X_val_sequences = tokenizer.texts_to_sequences(X_val)

# Testing:

X_test_sequences = tokenizer.texts_to_sequences(X_test)

In [32]:
print("Original text:")
print(X_train.iloc[0])

print("\nInteger sequence:")
print(X_train_sequences[0])

Original text:
much say one except probably worst early spate zombie movies may get watch another one revolt zombies month star john carradine intention building army service third reich seen much james baskett uncle remus song south plays leader also serves carradine manservant black comic mantan moreland reprises fraidy cat chauffeur role king zombies exotically named madame sul te wan carradine housekeeper unfortunately carradine supreme achievement zombification wife brings sorts trouble relatives turn remote abode lab inquire sudden death means fake funeral service actually proves disobedient indignant eventually persuading fellow zombies rise master also involved cowboy star bob steele still best known bit howard hawks big sleep plays u secret agent posing nazi posing sheriff thankfully director sekely would much better luck next genre effort day triffids

Integer sequence:
[14, 49, 4, 430, 128, 142, 289, 1, 823, 25, 94, 16, 29, 62, 4, 7911, 1116, 3148, 204, 191, 4360, 3438, 1178, 1075, 2165, 741, 18543, 32, 14, 472, 1, 1621, 1, 439, 1107, 185, 1613, 19, 2386, 4360, 1, 202, 573, 1, 1, 14455, 1, 1028, 13716, 105, 550, 1116, 1, 632, 12225, 1, 12454, 7288, 4360, 9447, 349, 4360, 5736, 3340, 1, 201, 812, 2419, 929, 4579, 340, 2754, 1, 3518, 1, 2025, 211, 684, 991, 3683, 2165, 64, 1483, 1, 1, 714, 1, 1474, 1116, 2042, 980, 19, 452, 2719, 204, 1675, 7816, 48, 39, 414, 118, 1588, 11467, 87, 1500, 185, 968, 894, 1291, 6251, 2452, 6251, 1958, 2285, 60, 1, 9, 14, 45, 1879, 243, 372, 633, 140, 1]

# Determine Sequence Length

In [33]:
sequence_lengths = [
    len(sequence)
    for sequence in X_train_sequences
]

print("Minimum length:", min(sequence_lengths))
print("Maximum length:", max(sequence_lengths))
print("Average length:", np.mean(sequence_lengths))
print("Median length:", np.median(sequence_lengths))

Minimum length: 3
Maximum length: 1154
Average length: 118.55683619075062
Median length: 88.0

In [34]:
print(
    "90th percentile:",
    np.percentile(sequence_lengths, 90)
)

print(
    "95th percentile:",
    np.percentile(sequence_lengths, 95)
)

90th percentile: 233.0
95th percentile: 307.0

# Padding

In [35]:
MAX_SEQUENCE_LENGTH = 200

# Training

X_train_padded = pad_sequences(
    X_train_sequences,
    maxlen=MAX_SEQUENCE_LENGTH,
    padding="post",
    truncating="post"
)

# Validation:

X_val_padded = pad_sequences(
    X_val_sequences,
    maxlen=MAX_SEQUENCE_LENGTH,
    padding="post",
    truncating="post"
)

# Testing:

X_test_padded = pad_sequences(
    X_test_sequences,
    maxlen=MAX_SEQUENCE_LENGTH,
    padding="post",
    truncating="post"
)

In [36]:
print("X_train shape:", X_train_padded.shape)
print("X_val shape:", X_val_padded.shape)
print("X_test shape:", X_test_padded.shape)

X_train shape: (34705, 200)
X_val shape: (7439, 200)
X_test shape: (7438, 200)

In [37]:
print("y_train shape:", y_train.shape)
print("y_val shape:", y_val.shape)
print("y_test shape:", y_test.shape)

y_train shape: (34705,)
y_val shape: (7439,)
y_test shape: (7438,)

In [38]:
y_train = np.array(y_train)
y_val = np.array(y_val)
y_test = np.array(y_test)


print(type(X_train_padded))
print(type(y_train))

print(X_train_padded.dtype)
print(y_train.dtype)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
int32
int64

In [39]:
sample_index = 0

print("Original review:")
print(X_train.iloc[sample_index])

print("\nCleaned review:")
print(X_train.iloc[sample_index])

print("\nToken sequence:")
print(X_train_sequences[sample_index])

print("\nPadded sequence:")
print(X_train_padded[sample_index])

print("\nSentiment label:")
print(y_train[sample_index])

Original review:
much say one except probably worst early spate zombie movies may get watch another one revolt zombies month star john carradine intention building army service third reich seen much james baskett uncle remus song south plays leader also serves carradine manservant black comic mantan moreland reprises fraidy cat chauffeur role king zombies exotically named madame sul te wan carradine housekeeper unfortunately carradine supreme achievement zombification wife brings sorts trouble relatives turn remote abode lab inquire sudden death means fake funeral service actually proves disobedient indignant eventually persuading fellow zombies rise master also involved cowboy star bob steele still best known bit howard hawks big sleep plays u secret agent posing nazi posing sheriff thankfully director sekely would much better luck next genre effort day triffids

Cleaned review:
much say one except probably worst early spate zombie movies may get watch another one revolt zombies month star john carradine intention building army service third reich seen much james baskett uncle remus song south plays leader also serves carradine manservant black comic mantan moreland reprises fraidy cat chauffeur role king zombies exotically named madame sul te wan carradine housekeeper unfortunately carradine supreme achievement zombification wife brings sorts trouble relatives turn remote abode lab inquire sudden death means fake funeral service actually proves disobedient indignant eventually persuading fellow zombies rise master also involved cowboy star bob steele still best known bit howard hawks big sleep plays u secret agent posing nazi posing sheriff thankfully director sekely would much better luck next genre effort day triffids

Token sequence:
[14, 49, 4, 430, 128, 142, 289, 1, 823, 25, 94, 16, 29, 62, 4, 7911, 1116, 3148, 204, 191, 4360, 3438, 1178, 1075, 2165, 741, 18543, 32, 14, 472, 1, 1621, 1, 439, 1107, 185, 1613, 19, 2386, 4360, 1, 202, 573, 1, 1, 14455, 1, 1028, 13716, 105, 550, 1116, 1, 632, 12225, 1, 12454, 7288, 4360, 9447, 349, 4360, 5736, 3340, 1, 201, 812, 2419, 929, 4579, 340, 2754, 1, 3518, 1, 2025, 211, 684, 991, 3683, 2165, 64, 1483, 1, 1, 714, 1, 1474, 1116, 2042, 980, 19, 452, 2719, 204, 1675, 7816, 48, 39, 414, 118, 1588, 11467, 87, 1500, 185, 968, 894, 1291, 6251, 2452, 6251, 1958, 2285, 60, 1, 9, 14, 45, 1879, 243, 372, 633, 140, 1]

Padded sequence:
[   14    49     4   430   128   142   289     1   823    25    94    16
    29    62     4  7911  1116  3148   204   191  4360  3438  1178  1075
  2165   741 18543    32    14   472     1  1621     1   439  1107   185
  1613    19  2386  4360     1   202   573     1     1 14455     1  1028
 13716   105   550  1116     1   632 12225     1 12454  7288  4360  9447
   349  4360  5736  3340     1   201   812  2419   929  4579   340  2754
     1  3518     1  2025   211   684   991  3683  2165    64  1483     1
     1   714     1  1474  1116  2042   980    19   452  2719   204  1675
  7816    48    39   414   118  1588 11467    87  1500   185   968   894
  1291  6251  2452  6251  1958  2285    60     1     9    14    45  1879
   243   372   633   140     1     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0]

Sentiment label:
0

In [40]:
import pickle

with open(
    "../Dataset/processed/tokenizer.pkl",
    "wb"
) as file:

    pickle.dump(tokenizer, file)

In [41]:
text_splits = {
    "X_train": X_train.tolist(),
    "X_val": X_val.tolist(),
    "X_test": X_test.tolist()
}

with open(
    "../Dataset/processed/text_splits.pkl",
    "wb"
) as file:
    pickle.dump(text_splits, file)

In [42]:
preprocessing_config = {
    "max_sequence_length": MAX_SEQUENCE_LENGTH,
    "num_words": 20000
}

with open(
    "../Dataset/processed/preprocessing_config.pkl",
    "wb"
) as file:

    pickle.dump(preprocessing_config, file)

In [43]:
np.save(
    "../Dataset/processed/X_train_padded.npy",
    X_train_padded
)

np.save(
    "../Dataset/processed/X_val_padded.npy",
    X_val_padded
)

np.save(
    "../Dataset/processed/X_test_padded.npy",
    X_test_padded
)

np.save(
    "../Dataset/processed/y_train.npy",
    y_train
)

np.save(
    "../Dataset/processed/y_val.npy",
    y_val
)

np.save(
    "../Dataset/processed/y_test.npy",
    y_test
)