In [2]:
import pandas as pd

# BaseLine Model

In [8]:
df = pd.DataFrame(
    {
        "Model": ["ANN", "RNN", "LSTM", "GRU", "Bi-LSTM"],
        "Accuracy": [0.874429, 0.497714, 0.865286, 0.872143, 0.864345],
        "Precision": [0.876513, 0.499779, 0.879622, 0.868966, 0.866129],
        "Recall": [0.872756, 0.909456, 0.847576, 0.877578, 0.863113],
        "F1 Score": [0.874631, 0.645069, 0.863302, 0.873251, 0.864618],
        "ROC-AUC": [0.948354, 0.500022, 0.932051, 0.935258, 0.935844],
    }
)

df

     Model  Accuracy  Precision    Recall  F1 Score   ROC-AUC
0      ANN  0.874429   0.876513  0.872756  0.874631  0.948354
1      RNN  0.497714   0.499779  0.909456  0.645069  0.500022
2     LSTM  0.865286   0.879622  0.847576  0.863302  0.932051
3      GRU  0.872143   0.868966  0.877578  0.873251  0.935258
4  Bi-LSTM  0.864345   0.866129  0.863113  0.864618  0.935844

# Optimization Results

In [3]:
optimization_results = pd.read_csv("../Dataset/optimization_results.csv")

In [4]:
optimization_results

,Experiment,Enhancement,Model,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,E1,DropOut 0.3,ANN,0.882764,0.900140,0.862041,0.880679,0.953827
1,E2,DropOut 0.5,ANN,0.882226,0.889768,0.873560,0.881590,0.955187
2,E3,BatchNormalization,ANN,0.882226,0.889768,0.873560,0.881590,0.954410
3,E4,Optimizers RMSprop,ANN,0.882226,0.889768,0.873560,0.881590,0.954376
4,E5,Learning Rate Rmsprop(0.0001),ANN,0.904679,0.904494,0.905706,0.905100,0.967430
...,...,...,...,...,...,...,...,...
61,E10,Learning Rate Rmsprop 0.0001,BI_LSTM,0.873353,0.877468,0.869006,0.873217,0.930012
62,E11,Batch Size 32,BI_LSTM,0.863404,0.878518,0.844629,0.861240,0.935813
63,E12,Batch Size 16,BI_LSTM,0.865017,0.852493,0.884008,0.867964,0.932680
64,E13,Early Stopping,BI_LSTM,0.870933,0.868456,0.875435,0.871932,0.933090
65,E14,LR Schedule,BI_LSTM,0.870261,0.872644,0.868203,0.870418,0.929214

In [5]:
top_results = optimization_results.sort_values(by="Accuracy" , ascending = False)

In [6]:
top_results.head()

,Experiment,Enhancement,Model,Accuracy,Precision,Recall,F1 Score,ROC-AUC
9,E10,Early Stopping,ANN,0.905216,0.900741,0.911599,0.906138,0.967254
8,E9,Batch Size 32,ANN,0.904948,0.905848,0.904634,0.905241,0.967277
4,E5,Learning Rate Rmsprop(0.0001),ANN,0.904679,0.904494,0.905706,0.905100,0.967430
10,E11,LR Scheduler,ANN,0.903334,0.901652,0.906242,0.903941,0.966973
5,E6,Learning Rate Adam(0.0001),ANN,0.896209,0.897877,0.894991,0.896431,0.963490

In [7]:
top_results = (
    top_results
    .sort_values(
        by=["Model", "Accuracy"],
        ascending=[True, False]
    )
    .groupby("Model")
    .head(1)
    .reset_index(drop=True)
)

top_results

,Experiment,Enhancement,Model,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,E10,Early Stopping,ANN,0.905216,0.900741,0.911599,0.906138,0.967254
1,E9,Learning Rate adam 0.0005,BI_LSTM,0.876042,0.881618,0.869810,0.875674,0.940581
2,E7,New Optimizers Rmsprop,GRU,0.891772,0.883447,0.903563,0.893392,0.959335
3,E8,learning rate adam 0.0001,LSTM,0.876714,0.883234,0.869274,0.876198,0.944330
4,E9,Learning rate adam 0.0005,RNN,0.523259,0.673469,0.097241,0.169944,0.538738