# Phase 3 – Probability & Inferential Statistics

## Objective

The objective of this notebook is to apply probability concepts and inferential statistical methods to the processed Hotel Booking Demand dataset. This analysis provides a statistical foundation for assumption testing and hypothesis testing in the subsequent phases.

## Import Libraries

In [8]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats

from scipy.stats import norm

pd.set_option("display.max_columns", None)

sns.set_theme(style="whitegrid")

print("Libraries Imported Successfully")

Libraries Imported Successfully

## Load Dataset

In [9]:
dataset_path = "../data/processed/final_hotel_bookings.csv"

df = pd.read_csv(dataset_path)

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

## Dataset Information

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 87225 entries, 0 to 87224
Data columns (total 39 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87225 non-null  str
 1   is_canceled                     87225 non-null  bool
 2   lead_time                       87225 non-null  int64
 3   arrival_date_year               87225 non-null  int64
 4   arrival_date_month              87225 non-null  str
 5   arrival_date_week_number        87225 non-null  int64
 6   arrival_date_day_of_month       87225 non-null  int64
 7   stays_in_weekend_nights         87225 non-null  int64
 8   stays_in_week_nights            87225 non-null  float64
 9   adults                          87225 non-null  int64
 10  children                        87225 non-null  float64
 11  babies                          87225 non-null  int64
 12  meal                            87225 non-null  str
 13  country                         86778 non-null  str
 14  market_segment                  87225 non-null  str
 15  distribution_channel            87225 non-null  str
 16  is_repeated_guest               87225 non-null  bool
 17  previous_cancellations          87225 non-null  int64
 18  previous_bookings_not_canceled  87225 non-null  int64
 19  reserved_room_type              87225 non-null  str
 20  assigned_room_type              87225 non-null  str
 21  booking_changes                 87225 non-null  int64
 22  deposit_type                    87225 non-null  str
 23  agent                           75086 non-null  float64
 24  company                         5237 non-null   float64
 25  days_in_waiting_list            87225 non-null  int64
 26  customer_type                   87225 non-null  str
 27  average_daily_rate              87225 non-null  float64
 28  required_car_parking_spaces     87225 non-null  int64
 29  total_of_special_requests       87225 non-null  int64
 30  reservation_status              87225 non-null  str
 31  reservation_status_date         87225 non-null  str
 32  hotel_label                     87225 non-null  int64
 33  total_stay_duration             87225 non-null  float64
 34  total_guests                    87225 non-null  float64
 35  lead_time_category              87225 non-null  str
 36  stay_type                       87225 non-null  str
 37  booking_season                  87225 non-null  str
 38  guest_status                    87225 non-null  str
dtypes: bool(2), float64(7), int64(14), str(16)
memory usage: 24.8 MB

## Dataset Shape

In [11]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 87225
Columns : 39

## First Five Records

In [12]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,average_daily_rate,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,hotel_label,total_stay_duration,total_guests,lead_time_category,stay_type,booking_season,guest_status
0,Resort Hotel,False,296,2015,July,27,1,0,0.0,2,0.0,0,BB,PRT,Direct,Direct,False,0,0,C,C,0,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,1,0.0,2.0,Very Long,Weekday,Summer,New
1,Resort Hotel,False,296,2015,July,27,1,0,0.0,2,0.0,0,BB,PRT,Direct,Direct,False,0,0,C,C,0,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,1,0.0,2.0,Very Long,Weekday,Summer,New
2,Resort Hotel,False,7,2015,July,27,1,0,1.0,2,0.0,0,BB,GBR,Direct,Direct,False,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02,1,1.0,2.0,Short,Weekday,Summer,New
3,Resort Hotel,False,13,2015,July,27,1,0,1.0,2,0.0,0,BB,GBR,Corporate,Corporate,False,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02,1,1.0,2.0,Short,Weekday,Summer,New
4,Resort Hotel,False,14,2015,July,27,1,0,2.0,2,0.0,0,BB,GBR,Online TA,TA/TO,False,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03,1,2.0,2.0,Short,Weekday,Summer,New

## Numerical Columns

In [13]:
numerical_columns = df.select_dtypes(
    include=["int64", "float64"]
).columns

print(numerical_columns)

Index(['lead_time', 'arrival_date_year', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies',
       'previous_cancellations', 'previous_bookings_not_canceled',
       'booking_changes', 'agent', 'company', 'days_in_waiting_list',
       'average_daily_rate', 'required_car_parking_spaces',
       'total_of_special_requests', 'hotel_label', 'total_stay_duration',
       'total_guests'],
      dtype='str')

## Descriptive Statistics

In [14]:
df[numerical_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
lead_time,87225.0,78.444918,81.052481,0.0,11.00,49.0,125.0,296.000
arrival_date_year,87225.0,2016.210398,0.686029,2015.0,2016.00,2016.0,2017.0,2017.000
arrival_date_week_number,87225.0,26.835036,13.669439,1.0,16.00,27.0,37.0,53.000
arrival_date_day_of_month,87225.0,15.816383,8.835459,1.0,8.00,16.0,23.0,31.000
stays_in_weekend_nights,87225.0,0.998899,0.993097,0.0,0.00,1.0,2.0,5.000
stays_in_week_nights,87225.0,2.577048,1.804803,0.0,1.00,2.0,4.0,8.500
adults,87225.0,2.000000,0.000000,2.0,2.00,2.0,2.0,2.000
children,87225.0,0.000000,0.000000,0.0,0.00,0.0,0.0,0.000
babies,87225.0,0.000000,0.000000,0.0,0.00,0.0,0.0,0.000
previous_cancellations,87225.0,0.000000,0.000000,0.0,0.00,0.0,0.0,0.000
previous_bookings_not_canceled,87225.0,0.184041,1.733072,0.0,0.00,0.0,0.0,72.000
booking_changes,87225.0,0.000000,0.000000,0.0,0.00,0.0,0.0,0.000
agent,75086.0,94.200250,113.205343,1.0,9.00,14.0,240.0,535.000
company,5237.0,182.970594,130.486644,6.0,47.00,169.0,263.0,543.000
days_in_waiting_list,87225.0,0.746334,10.001286,0.0,0.00,0.0,0.0,391.000
average_daily_rate,87225.0,105.524569,49.032923,0.0,72.25,98.2,134.1,226.875
required_car_parking_spaces,87225.0,0.084311,0.281666,0.0,0.00,0.0,0.0,8.000
total_of_special_requests,87225.0,0.698917,0.832058,0.0,0.00,0.0,1.0,5.000
hotel_label,87225.0,0.389281,0.487590,0.0,0.00,0.0,1.0,1.000
total_stay_duration,87225.0,3.575947,2.448157,0.0,2.00,3.0,5.0,13.500
total_guests,87225.0,2.000000,0.000000,2.0,2.00,2.0,2.0,2.000

## Conclusion

#### The processed dataset was successfully loaded and inspected. Numerical variables relevant to statistical analysis were identified, and descriptive statistics confirmed that the dataset is ready for probability and inferential statistical analysis.