In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import ( RandomForestRegressor,GradientBoostingRegressor )
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

In [2]:
from sklearn.metrics import ( mean_absolute_error, mean_squared_error, r2_score )

In [3]:
train = pd.read_csv("../dataset/cleaned/ready_to_train.csv")

train.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,SalePrice
0,-1.730865,0.454631,-0.237456,-0.333244,0.652644,-0.564161,1.053246,0.878668,1.230517,0.614224,...,-0.060409,-0.359481,-0.046438,0.329514,-0.053838,-0.095448,-0.125394,0.383663,-0.365276,208500.0
1,-1.728492,-1.143813,0.633321,-0.013189,-0.073068,2.030907,0.156179,-0.429577,-0.809621,1.242296,...,-0.060409,-0.359481,-0.046438,0.329514,-0.053838,-0.095448,-0.125394,0.383663,-0.365276,181500.0
2,-1.726120,0.454631,-0.063300,0.446022,0.652644,-0.564161,0.986797,0.830215,1.157359,0.106224,...,-0.060409,-0.359481,-0.046438,0.329514,-0.053838,-0.095448,-0.125394,0.383663,-0.365276,223500.0
3,-1.723747,0.682185,-0.527714,-0.027104,0.652644,-0.564161,-1.870528,-0.720298,-0.809621,-0.517230,...,-0.060409,-0.359481,-0.046438,0.329514,-0.053838,-0.095448,-0.125394,NaN,-0.365276,140000.0
4,-1.721374,0.454631,0.865528,1.283733,1.378355,-0.564161,0.953572,0.733308,1.453554,0.496460,...,-0.060409,-0.359481,-0.046438,0.329514,-0.053838,-0.095448,-0.125394,0.383663,-0.365276,250000.0

In [4]:
missing = train.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

missing

RoofStyle_Gable         319
MSZoning_RL             309
SaleCondition_Normal    262
Condition1_Norm         200
SaleType_WD             193
ExterCond_TA            178
BsmtFinType2_Unf        166
LandContour_Lvl         149
Electrical_SBrkr        125
PavedDrive_Y            120
BsmtCond_TA             112
Functional_Typ          100
CentralAir_Y             95
GarageQual_TA            68
GarageCond_TA            53
Heating_GasA             32
RoofMatl_CompShg         26
Condition2_Norm          15
Street_Pave               6
dtype: int64

In [5]:
numerical_columns = train.select_dtypes(include=["int64", "float64"]).columns

for column in numerical_columns:
    train[column] = train[column].fillna(train[column].median())

In [6]:
X = train.drop("SalePrice", axis=1)

y = train["SalePrice"]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [8]:
X_train.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
254,-1.128206,-1.143813,0.052803,-0.347160,-0.798780,0.473866,-0.475091,-1.350194,-0.809621,1.112987,...,-0.060409,-0.060409,-0.359481,-0.046438,0.329514,-0.053838,-0.095448,-0.125394,0.383663,-0.365276
1066,0.798404,0.454631,-0.585766,-0.503848,-0.073068,1.511894,0.720999,0.442586,-0.809621,-1.015994,...,-0.060409,-0.060409,-0.359481,-0.046438,0.329514,-0.053838,-0.095448,-0.125394,0.383663,-0.365276
638,-0.217100,-0.560012,-0.121352,-0.242237,-0.798780,1.511894,-2.036652,-1.689368,-0.809621,-1.015994,...,-0.060409,-0.060409,-0.359481,-0.046438,0.329514,-0.053838,-0.095448,-0.125394,0.383663,-0.365276
799,0.164901,0.186240,-0.527714,-0.681131,-0.798780,1.511894,-1.139585,-1.689368,1.327128,0.297878,...,-0.060409,-0.060409,-0.359481,-0.046438,0.329514,-0.053838,-0.095448,-0.125394,0.383663,-0.365276
380,-0.829249,0.186240,-1.108232,-1.293411,-0.798780,0.473866,-1.571506,-1.689368,-0.809621,-0.512612,...,-0.060409,-0.060409,-0.359481,-0.046438,0.329514,-0.053838,-0.095448,-0.125394,0.383663,-0.365276

In [9]:
X_test.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
892,0.385559,-1.143813,0.052803,-0.343263,-0.073068,2.030907,-0.275742,0.878668,-0.809621,0.514933,...,-0.060409,-0.060409,-0.359481,-0.046438,0.329514,-0.053838,-0.095448,-0.125394,0.383663,-0.365276
1105,0.890939,0.454631,1.678252,0.726001,1.378355,-0.564161,0.754224,0.491040,1.466535,1.366987,...,-0.060409,-0.060409,-0.359481,-0.046438,0.329514,-0.053838,-0.095448,-0.125394,0.383663,-0.365276
413,-0.750951,-0.560012,-0.759921,-0.191306,-0.798780,0.473866,-1.471832,-1.689368,-0.809621,-1.015994,...,-0.060409,-0.060409,-0.359481,-0.046438,0.329514,-0.053838,-0.095448,-0.125394,0.383663,-0.365276
522,-0.492330,0.186240,-1.108232,-1.293411,-0.073068,1.511894,-0.807338,-1.689368,-0.809621,-0.094667,...,-0.060409,-0.060409,-0.359481,-0.046438,0.329514,-0.053838,-0.095448,-0.125394,0.383663,-0.365276
1036,0.727224,-1.143813,1.155787,0.904675,2.104067,-0.564161,1.186145,1.120936,0.836436,1.343896,...,-0.060409,-0.060409,-0.359481,-0.046438,0.329514,-0.053838,-0.095448,-0.125394,0.383663,-0.365276

In [10]:
y_train.head()

254     145000.0
1066    178000.0
638      85000.0
799     175000.0
380     127000.0
Name: SalePrice, dtype: float64

In [11]:
y_test.head()

892     154500.0
1105    325000.0
413     115000.0
522     159000.0
1036    315500.0
Name: SalePrice, dtype: float64

In [12]:
models = {
    "Linear Regression": LinearRegression(),

    "Decision Tree": DecisionTreeRegressor(
        random_state=42
    ),

    "Random Forest": RandomForestRegressor(
        random_state=42
    ),

    "Gradient Boosting": GradientBoostingRegressor(
        random_state=42
    ),

    "XGBoost": XGBRegressor(
        random_state=42
    ),

    "LightGBM": LGBMRegressor(
        random_state=42
    ),

    "CatBoost": CatBoostRegressor(
        verbose=0,
        random_state=42
    )
}
results = []

for model_name, model in models.items():

    model.fit( X_train, y_train )

    predictions = model.predict( X_test )

    print(model_name, "\n", predictions)

    mae = mean_absolute_error( y_test, predictions )

    mse = mean_squared_error(y_test,predictions)

    r2 = r2_score( y_test, predictions)

    results.append({ "Model": model_name, "MAE": mae, "MSE": mse, "R2 Score": r2})

Linear Regression
 [157419.0454596  316604.8313203  109005.33926524 184576.62039245
 305558.17592596  71093.87635865 238685.324581   143457.33326713
  61705.65136701 139594.79532639 142397.93931769 111184.8496826
 122464.30617995 225296.73666354 180130.23333188 133308.64165112
 194062.25444271 135169.72519935 123623.51509578 219728.52257461
 172474.69915033 211582.45924074 172042.97560656 122747.64665839
 204443.30557587 152925.8205753  195073.55810333 110750.04859708
 177110.41232348 201013.06173326 133844.92372394 275123.45524825
 249326.10063805 113632.96573968 249352.78329858 144409.46912033
 136458.92839322 207966.47886612 317416.4557148  108437.70101171
 138466.9775855  229274.22840746 103592.49374301 312077.57820148
 133365.99976074 135289.80553309 105269.52436904 134041.02080542
 354862.96303746 126588.20682019 116226.10558771 210152.87784956
 112750.99133131 293597.73985722 161512.18571345 239963.28326611
 198051.22367695 175413.53370211 126732.70768119  87342.12789714
  64369.43820414 171729.13581375 304017.80045692 255187.62958783
 281665.55457155 209776.5953463  100178.12638435 281510.52129423
 134978.34619994 173032.40583893 136890.9826536  122113.95417665
 106387.03620883  26907.42190005 370182.34893614 199793.39248403
 294682.59355322 290576.40233912 155116.59462846 129312.32556282
 114959.89069761   9886.92541097 137906.56213947 104433.93024299
 161276.29358555 149334.25373689 250455.34472835 211116.42127861
 146989.91354631 180778.23496914 144534.71554238 152770.48120024
 127139.03804356 273735.0874733  122740.97113343 181742.08135179
 186635.45313389 162871.61472262 201477.16084976 271419.43177447
 156905.30577483 206551.15283893 256475.26634647 147496.18816252
 203525.08164256 174249.7507073  160045.34016301 268684.69657753
 156774.74796746 226961.34556903  70865.50591824 135025.58139499
 144188.36677287 140994.3952505  201491.90748074 119447.46754919
 106077.65172781 111947.72501771 105565.98544231 265150.74412268
 123081.42659759 148543.45499287 185372.91231897 193207.61391766
 198134.59087289 133485.65957881 235423.91461405  90762.1052279
 152535.97173264 172885.59766023 192539.81240589 307442.82713687
 195991.73168796 143240.35340045  50644.76008025 328621.35089241
 297028.15381445 135517.71864337 232081.50566136 397673.28057283
 333640.89456547 134396.11762599 173334.06282485 157690.10477227
 145865.89460894 117537.77532471 235162.24840224 198993.43489306
 133636.19113543  40900.35948004 128305.69759616 150333.06937833
 275394.30746009 148115.93611677  76075.22060616 108111.82076831
 138274.66053266 143738.72954377  82566.1068581  128419.26086308
 201231.40036191 119211.55993234 278506.30684158 152350.46103351
 107759.35464287 134245.29781678 231470.01457441 310510.70086553
 383604.250172   227217.49617122 340236.95085695  85538.12809748
 106401.10924946 136444.13462238 293229.85445637 115793.04361013
 115672.78645956 213609.2329091  125819.6411636  170452.97352411
 184628.27249722 152424.76758588 129327.73817403 139383.41739636
 243473.99911666 119446.20605699 267099.72998651 219242.4432702
 202424.91744551  71443.0128661  122801.43679998 125324.21289491
 153870.76908911 137682.19175384 198220.0054489  198627.11579424
 207382.95633021  95563.14109724 200359.77856288 122440.25820326
 250628.51706664 207703.07286108 127109.22420115 301975.06526439
 198273.06583304 116971.87862941 227593.62128593 134393.76886524
 135884.07755612 100744.01608989 222273.49794736 143641.21002596
 108905.38881296 168525.25564667 228476.29164003 253055.64592457
 205258.27447926 130482.5842292  109755.21529173 105077.20757302
 137696.78034279 223588.88310412 219799.1041861   99530.25283041
 229100.37344177 147429.9856467   81315.56593758  89873.02864419
 166728.54213357 116580.42876793  96947.41412071 172561.95630971
 119577.957661   141551.34932529 227722.04720309 137880.10998043
 195783.86138682 168336.48761962 242070.45293513 110235.88833606
 111077.95367991 261075.3186631  206158.18698503 357428.68825089
 189770.49691828 129283.43620991 158393.13312351 190995.4945574
 154258.61689745  93400.496871   183767.8583156  161934.23017262
 140097.36051702  94035.63651929 139236.60285014 136801.01815101
 125202.45315421 135005.92035902 171368.38641546 242459.7962056
 283447.72235602 195167.80050215 134407.51605397 225100.93429346
 297606.7454424  230997.51709146 168468.38934372 141782.02121456
 105480.91314119 180942.10684658 351624.56482207 218296.49110159
 234938.13690429  76812.19557547  63888.19386725 142160.53007559
 144551.43513527 276288.85647027 289801.5370798  144418.32110249
 209360.69745756 100595.70183162 206259.33025618 103101.41274779
 274856.91591622 193678.20590552 216987.35185761 158348.49066483
 278503.72346998 192874.92064383  92068.96487822 119228.6187604 ]
Decision Tree
 [158500.  286000.  120000.  210000.  295493.   81000.  205000.  130000.
  81000.  141500.  189950.  100000.  120500.  201000.  179000.  139400.
 186500.  136000.  118000.  194000.  149900.  227000.  193000.  135000.
 185500.  185000.  164990.   93000.  172400.  196000.  116000.  233000.
 189000.  109900.  282922.  124500.  104900.  170000.  340000.  106500.
 110000.  268000.  119500.  340037.5 126500.  140000.   98000.  100000.
 340037.5 128500.  110000.  208900.  109900.  340037.5 140000.  260400.
 170000.  160000.  145000.  110000.   60000.  181000.  309000.  230000.
 314813.  235000.  120000.  340037.5 123500.  168500.  124000.   91500.
 106500.   87500.  340037.5 181000.  340000.  328000.  139000.  127000.
  85400.   76000.  132250.   62383.  163000.  124000.  252000.  190000.
 131500.  176500.  124900.  175000.  158000.  328000.  110000.  181000.
 130000.  140000.  205000.  192000.  157500.  193000.  180000.  116900.
 228950.  177000.  138000.  340037.5 142500.  170000.   55000.  119200.
 132500.  124000.  237000.  130500.  100000.  120500.  158000.  270000.
 184000.  141000.  178000.  210000.  190000.  142000.  263000.  102000.
 148000.  157000.  184900.  340037.5 225000.  128000.   80000.  340037.5
 340037.5 144000.  235000.  340037.5 340037.5 158000.  189000.  206900.
 157000.  134500.  214000.  180500.  110000.   58500.  108500.  173733.
 223000.  139000.   85000.  124000.  107000.  163000.   88000.  158000.
 202500.  165500.  270000.  148000.  158000.  119000.  184000.  340037.5
 340037.5 200000.  340037.5 100000.  118500.  177000.  257000.   79000.
 135000.  180000.   91500.  177000.  167500.   98000.  122000.  178000.
 228500.  143000.  270000.  154000.  202665.   83500.  130000.  108000.
 105000.  139000.  176432.  117000.  280000.  100000.  258000.  114504.
 302000.  190000.  127500.  340037.5 185500.  126000.  168000.  126500.
 140200.  122000.  238000.  110000.   55000.  168500.   82500.  236500.
 174000.  132500.   60000.  100000.  144000.  212000.  175000.  108000.
 244600.  145000.  108500.  108000.  130500.  121600.  112000.  187500.
 119500.  181000.  215000.  140000.  194000.  146000.  192000.  133000.
 109500.  263000.  248000.  340037.5 187000.  154000.  153000.  155000.
 132500.  110000.  167500.  163900.  128500.   96500.  139000.  140000.
 117000.   95000.  130000.  233230.  340037.5 162500.  108000.  214000.
 216837.  200000.  165000.  149300.  126500.  162000.  340037.5 189000.
 239799.  101000.   90000.  151000.  130000.  266000.  256000.  169500.
 248000.   84500.  186500.   96500.  319000.  163000.  235000.  121600.
 213250.  184000.  141500.  121600. ]
Random Forest
 [143696.    304831.735 115770.25  154562.14  298363.935  80790.5
 211063.04  151136.     83194.83  132167.55  162471.    122377.65
 102828.5   208741.1   176593.    129472.75  194680.55  136742.5
 114971.5   206582.935 159910.55  214815.64  175261.91  122298.1
 196807.58  172807.37  185555.84  101404.66  176916.92  192474.48
 121011.64  253609.165 171913.75  110532.    257823.24  148062.
 138432.17  205620.    314553.43  104605.31  121234.5   235581.75
 122278.    321966.71  136768.93  140085.12  117080.66  128286.33
 333590.58  144251.55  121374.33  199184.    127202.05  295030.73
 138786.    235694.05  199305.05  152021.05  145971.61  108984.5
  77340.33  148813.    305764.395 252502.275 289601.07  203744.44
 112110.    316792.28  118973.    163761.08  129090.94  132625.71
 113658.83   95312.5   334859.985 173670.23  322828.655 301037.16
 137389.25  121662.5   100337.04  102484.99  125329.5   103172.41
 155921.39  132889.66  263236.325 196843.72  139358.    180304.65
 144106.31  166488.64  123586.    262660.75  127054.69  177158.13
 166927.71  161241.12  217363.18  240179.55  178904.5   206625.87
 274915.685 154454.29  187574.82  157712.9   144370.75  288597.895
 142113.3   193075.03   61656.5   131551.75  133226.5   135303.03
 218184.95  115108.    112818.25  111673.    150257.46  267071.51
 165394.91  142009.87  179070.55  176429.27  184153.3   131483.75
 240178.27  113293.    146509.75  177173.65  191755.    332203.855
 202633.78  138311.48   81795.    317897.69  314556.17  128056.26
 232159.32  334100.43  326812.895 126810.    178266.2   159988.05
 139373.25  120706.46  223730.84  201365.27  127037.83   74217.
 106890.5   134470.82  218456.175 153554.68   99931.79  138592.18
 140067.84  146679.25   80657.83  131560.    215205.45  151783.51
 286853.085 156389.21  116860.16  121633.1   206261.01  314257.58
 337435.18  225499.27  323553.045  99592.    118944.66  160346.8
 293185.795 154643.89  138309.88  208207.99  121012.91  167266.16
 161118.32  108007.    136349.85  158349.34  265481.045 151792.14
 285996.195 203224.34  192418.54   84621.    124942.83  116243.91
 124394.84  147005.69  184088.71  166385.34  219194.57   99303.5
 213018.545 111026.34  221404.98  192988.66  120944.24  322187.495
 193024.64  131218.5   240398.    138426.5   143231.15  115788.5
 247767.13  139746.65  115444.33  160627.83  192710.355 265880.
 180263.06  139082.5   125870.55  137198.21  140753.1   227915.1
 188242.    106896.04  240039.63  145549.25  104124.5   110898.5
 167763.5   111090.5   103599.5   182927.22  116829.87  141193.
 237998.765 130524.02  196588.29  143992.85  249297.21  121018.82
 108773.5   243959.395 211684.53  326684.055 186122.9   126622.5
 163231.2   157632.35  143373.48  101558.99  181944.67  173412.36
 140364.86   96981.62  145825.    142417.87  115144.35  110093.84
 178118.22  270435.285 310809.47  160087.96  127852.5   228294.21
 249708.91  203026.46  168047.47  139049.5   121551.    170300.35
 332757.9   214312.27  232129.36  110893.31  100794.64  140445.5
 140699.9   284168.025 188027.84  149284.88  207320.52   98058.5
 193992.82  110732.08  307852.915 172102.26  225646.95  114101.25
 243936.815 179666.11  135137.74  114438.   ]
Gradient Boosting
 [143000.1096856  313117.91488858 125539.85091438 152170.54356161
 297002.24120652  83346.66390386 230107.11129012 143737.57514519
  83941.61413365 131527.74569697 152650.53520129 130696.85491129
 115467.6938765  203413.38521409 173984.84442708 136696.71428226
 187909.81484509 139355.07000731 116317.50054785 210826.13278036
 170605.70438001 231096.35825617 162440.00727379 124445.69965943
 197707.99345976 160403.00230552 197653.6672032  113741.91709041
 169535.29628946 183455.97411309 114960.66700577 258589.08873717
 236098.14946768 114604.55564226 257953.46344378 146562.64233566
 137384.5021416  206297.03964805 323317.56673144 112392.86402226
 127295.33443381 234637.85464184 116059.35890861 316292.18680011
 126706.10096729 109668.95210102 113620.94584092 128997.38070858
 349716.2069573  138049.51271092 120529.18878679 202779.345236
 114465.76116214 297809.76077281 146573.20139899 251401.41464901
 185855.35684375 159355.84709237 145029.87745171 102099.43242239
  78797.72023399 154089.8222828  306557.85172051 264753.43045071
 283986.62113076 193886.385567   106396.38387131 313511.85154832
 129294.93152212 160189.35587207 124308.10693718 122593.32371158
 113951.14867897  92158.80156963 335233.30591715 169293.82149714
 306757.19481539 297726.35615836 135876.53530161 117952.51187373
 104828.18442485  78257.76604712 125626.89906534  91059.20324326
 152186.66208722 129324.01825297 278729.39766846 202510.21263488
 146106.28919422 177019.50195758 140932.94733699 155161.25707784
 127465.09431038 264498.74838276 124331.93916585 173431.37807546
 171405.84458673 168327.66419895 208442.37777733 241760.95267468
 169122.7985939  201424.67853649 266140.59819444 148242.9241556
 187981.92083141 142008.91984033 151762.85321777 278041.21420549
 141356.26916319 177235.32507759  59743.93291418 123081.58259095
 136501.4155191  127889.8260404  197265.9564125  119893.93719473
 110644.25737349 110920.095012   127203.80588107 273118.38731987
 167033.34088906 145257.45191552 171795.47166946 181523.75533539
 171329.74846848 137551.36274943 234344.6455756  110192.53625773
 142720.6185632  176658.43005337 188435.90186627 327760.29909777
 194084.75579846 118004.17399829  66196.26100088 324842.04463421
 330876.92388484 127159.55290976 213867.60278575 331323.86655381
 324166.68043675 137196.46496206 169104.30189113 155550.1096389
 143192.03664035 132096.2580931  248990.0447229  186625.84417494
 128589.67949278  57216.15453888 114682.10278628 140197.56743877
 217139.71160877 160941.4320595  101371.79103973 122565.7542127
 154646.36372087 138999.07872546  89493.96132764 136011.12832687
 217271.46562525 150719.87859574 299701.97313268 150404.4048602
 110519.57508451 139966.63155562 216791.93367939 322706.77918839
 336794.16638167 243056.45059457 333848.86406253  94249.23311926
 111177.82262071 152001.28520239 287615.45862505 153019.54830484
 130801.80537772 207306.87930638 115146.3639546  162255.05530816
 181670.22224006 106872.93608562 129840.17852371 155130.89035951
 275917.5759242  146131.23377202 305756.73160201 206242.86087352
 183127.73444968  83023.73722903 115530.11105809 107228.54169505
 138926.82465128 145767.95279336 168206.81859212 166756.95797929
 229656.20298271  99792.21027419 212642.73784102 117636.63210269
 221045.6830835  179056.14174759 123525.14693396 315247.98777299
 189843.34343158 127553.29691091 261967.92649154 140517.05452881
 146825.25150875 118079.66112555 243629.88352227 135567.46864989
 114825.24825024 152700.68603717 211839.47585075 278433.19198296
 168296.86460393 142882.80889565 118278.70718031 136419.0920232
 140664.34727327 221874.57246297 206875.81162993  98015.16610077
 241665.03955239 149092.29764834  94289.88967568 107250.23956915
 164977.10276728 111477.98407879 105836.41651994 185326.06768668
 120711.86001717 144030.47278954 229145.91725066 132033.02321183
 199780.38383076 150371.82308968 246533.85650599 126957.95934531
 115044.52567294 256095.75326324 194801.60473234 334864.06428449
 188370.39448442 121917.97733543 149584.11673117 164586.26491497
 144337.82105157  90768.9403566  183980.28515095 169094.54556685
 133932.93785762  89427.22322159 139104.16682712 138117.77270353
 113228.16209533 107504.31955311 174259.7345674  280989.67968511
 289006.23649397 162021.25621759 131016.02657585 238118.20080452
 263275.09301738 206894.44764463 167531.58669812 140585.63171545
 122953.27157716 172022.87414672 338547.07213721 213706.84802725
 232802.4091005   89520.20837369 105185.4026225  132394.48995402
 156617.98300489 274092.427666   215674.39978076 152777.81966162
 196077.57084584  90731.32566006 201076.05407905 113477.21063551
 306440.18489589 182436.5355811  215382.11460481 128806.33265521
 241807.25684152 179294.26961781 126450.16000967 120373.61507208]
XGBoost
 [144050.44  308332.56  118911.21  166704.06  286866.2    77887.63
 227503.27  146990.73   85494.11  136474.14  159924.34  124516.516
 100273.516 207516.42  176513.3   134632.16  188300.92  125939.195
 109998.6   204608.05  163022.73  220707.73  169730.73  126333.42
 207212.19  162350.34  201578.9    91074.516 177897.52  194158.44
 127146.484 253973.78  192823.61  111653.68  239614.97  142926.83
 124689.5   205919.4   329767.7   105855.01  126544.85  237166.31
 118105.24  337082.66  129496.664 138332.61  115318.17  127202.484
 323947.7   139503.81  113709.98  197736.83  109203.24  275603.75
 146080.64  241753.72  196789.06  150564.64  145066.55   97505.695
  80360.55  162063.23  298666.5   281199.56  271868.06  228099.9
 106340.02  320229.62  128509.32  157759.47  128134.54  119449.41
 112851.35   85982.55  346740.    179930.05  336837.06  301941.78
 152450.7   119857.6   105836.086  76845.336 121474.    103602.35
 158653.78  129953.41  252624.66  182949.64  143526.25  173904.95
 137418.38  163239.9   124533.79  265458.34  115376.6   163044.56
 159275.61  157906.38  238044.66  214196.48  186468.89  219482.42
 249509.56  149609.25  200867.16  157994.53  148336.61  268121.38
 142421.62  182008.28   67643.68  118132.62  150832.47  140853.6
 219506.23  110064.34  109341.695 101270.16  139386.44  270597.56
 169556.48  146231.39  174837.72  194995.78  166222.42  143045.23
 237075.52  113535.766 128060.05  174596.58  187341.56  320937.2
 195612.47  154205.25   75155.66  306800.06  342487.22  142009.34
 238195.81  323543.25  326715.1   138804.11  176289.56  157139.31
 147284.94  125455.92  233224.72  189626.62  124160.484  60726.17
 109418.42  143973.14  222210.52  160954.03   97562.56  128152.83
 141333.34  131768.3    97068.84  136961.2   201870.34  162077.8
 296378.9   157621.48  108966.64  102089.91  207417.77  334611.3
 333711.97  219280.81  311260.28   95302.66  115226.33  146710.11
 273643.97  146988.    126358.64  204375.31  126853.625 176322.1
 176414.7    98226.73  141230.95  142511.94  267162.2   140751.34
 287184.47  190574.92  191054.22   82772.8   127404.484 105929.914
 136341.77  139381.6   184092.53  165020.56  219024.38   95012.164
 220932.4   122675.94  206354.86  197271.36  134628.89  337497.75
 193350.22  125659.1   240092.14  140631.39  149897.86  110128.07
 228999.72  144695.3   115540.51  159056.2   190723.11  280379.44
 178489.2   136980.11  124219.36  120435.68  150998.42  236700.4
 195017.17  101206.17  241782.58  150952.7   102944.695 122101.76
 164899.73  111071.26  103168.15  184678.06  117062.016 142044.03
 257472.2   123696.66  197154.12  153068.7   232230.28  104248.72
 108677.7   232512.94  206489.16  324671.25  187247.05  122566.484
 151533.36  140416.39  140394.78   90725.04  183118.64  166028.08
 147827.47   92790.01  147756.52  130848.91  120111.875 101351.33
 177440.5   274784.9   288964.2   176503.97  133651.73  238949.61
 266790.72  198685.62  169275.64  140638.5   126356.57  165938.31
 328615.72  206455.67  232256.56  101221.12   86984.2   144302.36
 128624.23  257172.78  183675.81  148207.6   193184.38   88376.78
 201205.89  102532.73  324529.5   177728.27  216278.81  113839.164
 233359.23  173781.78  135204.08  107978.766]
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001006 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3203
[LightGBM] [Info] Number of data points in the train set: 1168, number of used features: 123
[LightGBM] [Info] Start training from score 178189.621575
LightGBM
 [142139.69977481 294061.71647456 111063.76470361 163350.17297581
 311570.72181961  70927.6592029  228695.69082759 143473.75528687
  69429.26862068 130033.17857933 155300.92329533 126834.40643818
 105885.55106706 199465.0130001  176319.77745498 134055.38658366
 190791.68888093 140707.82438434 115995.65332264 213589.28926484
 144988.92165104 218124.71763824 168157.99606858 122237.39039951
 195828.54668883 170348.76223879 202518.98190626  97397.84733263
 176678.67328509 201312.18748792 121099.21805554 260493.82618789
 186772.42462577 105310.20005792 256133.95336821 147683.37003041
 117255.88104558 207424.65125049 306966.35308359 109812.9024584
 127178.98984728 238804.7701545  117805.89060506 332781.71878067
 130813.62210955 110489.99133919 111803.53320635 119298.66135783
 344793.61539066 146462.96255114 109382.78543787 183804.2479144

In [13]:
results

[{'Model': 'Linear Regression',
  'MAE': 15772.649826786359,
  'MSE': 535667665.6348231,
  'R2 Score': 0.890439705673151},
 {'Model': 'Decision Tree',
  'MAE': 22591.56678082192,
  'MSE': 1049319981.4152397,
  'R2 Score': 0.785382218524142},
 {'Model': 'Random Forest',
  'MAE': 14800.120291095891,
  'MSE': 425196071.9312296,
  'R2 Score': 0.9130344992315378},
 {'Model': 'Gradient Boosting',
  'MAE': 14113.775134569776,
  'MSE': 392235499.18901104,
  'R2 Score': 0.9197759366609173},
 {'Model': 'XGBoost',
  'MAE': 15707.820713827055,
  'MSE': 466106912.282106,
  'R2 Score': 0.9046669907975746},
 {'Model': 'LightGBM',
  'MAE': 13997.545370467713,
  'MSE': 382230236.00884634,
  'R2 Score': 0.9218223166258857},
 {'Model': 'CatBoost',
  'MAE': 12765.161892304048,
  'MSE': 329486095.5778331,
  'R2 Score': 0.9326100940490201}]

In [14]:
results = pd.DataFrame(results)

results.sort_values( by="R2 Score", ascending=False )

               Model           MAE           MSE  R2 Score
6           CatBoost  12765.161892  3.294861e+08  0.932610
5           LightGBM  13997.545370  3.822302e+08  0.921822
3  Gradient Boosting  14113.775135  3.922355e+08  0.919776
2      Random Forest  14800.120291  4.251961e+08  0.913034
4            XGBoost  15707.820714  4.661069e+08  0.904667
0  Linear Regression  15772.649827  5.356677e+08  0.890440
1      Decision Tree  22591.566781  1.049320e+09  0.785382

# Model Training completed