In [22]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import ( RandomForestRegressor,GradientBoostingRegressor )
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

In [23]:
from sklearn.metrics import ( mean_absolute_error, mean_squared_error, r2_score )

In [24]:
train = pd.read_csv("../dataset/cleaned/train_processed.csv")

train.head()

,LotArea,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,...,GarageArea,OpenPorchSF,ExterQual_Gd,ExterQual_TA,Foundation_PConc,BsmtQual_TA,BsmtFinType1_GLQ,KitchenQual_TA,GarageFinish_Unf,SalePrice
0,-0.333244,0.652644,1.053246,0.878668,1.230517,-0.488321,-0.830489,0.428636,0.789741,0.981148,...,0.373509,0.863737,1.411313,-1.278819,1.120968,-0.941438,1.578868,-1.006873,-0.941438,208500.0
1,-0.013189,-0.073068,0.156179,-0.429577,-0.809621,0.532289,0.289638,-0.502349,0.789741,-0.316385,...,-0.051541,-1.077559,-0.708560,0.781971,-0.892086,-0.941438,-0.633365,0.993174,-0.941438,181500.0
2,0.446022,0.652644,0.986797,0.830215,1.157359,-0.327437,-0.653917,0.586571,0.789741,-0.316385,...,0.663315,0.691611,1.411313,-1.278819,1.120968,-0.941438,1.578868,-1.006873,-0.941438,223500.0
3,-0.027104,0.652644,-1.870528,-0.720298,-0.809621,-0.739702,-0.540801,0.443182,-1.026041,0.332382,...,0.827539,0.608034,-0.708560,0.781971,-0.892086,1.062205,-0.633365,-1.006873,1.062205,140000.0
4,1.283733,1.378355,0.953572,0.733308,1.453554,0.238172,-0.033157,1.442744,0.789741,1.629914,...,1.764579,1.012147,1.411313,-1.278819,1.120968,-0.941438,1.578868,-1.006873,-0.941438,250000.0

In [25]:
missing = train.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

missing

Series([], dtype: int64)

In [26]:
numerical_columns = train.select_dtypes(include=["int64", "float64"]).columns

for column in numerical_columns:
    train[column] = train[column].fillna(train[column].median())

In [27]:
X = train.drop("SalePrice", axis=1)

y = train["SalePrice"]

In [28]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [29]:
X_train.head()

,LotArea,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,...,GarageCars,GarageArea,OpenPorchSF,ExterQual_Gd,ExterQual_TA,Foundation_PConc,BsmtQual_TA,BsmtFinType1_GLQ,KitchenQual_TA,GarageFinish_Unf
254,-0.347160,-0.798780,-0.475091,-1.350194,-0.809621,0.663007,0.433103,-0.394289,-1.026041,-0.965151,...,-1.030859,-0.853338,-1.077559,-0.708560,0.781971,-0.892086,1.062205,-0.633365,0.993174,-0.941438
1066,-0.503848,-0.073068,0.720999,0.442586,-0.809621,-0.631608,-0.987749,0.139781,0.789741,0.332382,...,0.315946,-0.437949,0.669208,1.411313,-1.278819,1.120968,-0.941438,-0.633365,0.993174,-0.941438
638,-0.242237,-0.798780,-2.036652,-1.689368,-0.809621,-0.639150,-0.996025,-1.470740,-1.026041,-1.613917,...,-2.377664,-2.273390,-1.077559,-0.708560,0.781971,-0.892086,-0.941438,-0.633365,0.993174,1.062205
799,-0.681131,-0.798780,-1.139585,-1.689368,1.327128,-0.802548,-0.485622,0.549165,-1.026041,0.332382,...,-1.030859,-1.114164,-1.077559,-0.708560,0.781971,-0.892086,-0.941438,-0.633365,-1.006873,1.062205
380,-1.293411,-0.798780,-1.571506,-1.689368,-0.809621,-0.060972,-0.361470,0.389152,0.789741,-0.316385,...,-1.030859,-0.785717,-1.077559,-0.708560,0.781971,-0.892086,1.062205,-0.633365,-1.006873,1.062205

In [30]:
X_test.head()

,LotArea,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,...,GarageCars,GarageArea,OpenPorchSF,ExterQual_Gd,ExterQual_TA,Foundation_PConc,BsmtQual_TA,BsmtFinType1_GLQ,KitchenQual_TA,GarageFinish_Unf
892,-0.343263,-0.073068,-0.275742,0.878668,-0.809621,0.021984,-0.245595,-0.905499,-1.026041,-0.316385,...,-1.030859,-0.998241,-1.077559,-0.708560,0.781971,-0.892086,1.062205,1.578868,0.993174,-0.941438
1105,0.726001,1.378355,0.754224,0.491040,1.466535,1.037566,0.946264,2.323855,0.789741,1.629914,...,0.315946,1.165646,0.567106,1.411313,-1.278819,1.120968,-0.941438,1.578868,-1.006873,-0.941438
413,-0.191306,-0.798780,-1.471832,-1.689368,-0.809621,-0.106221,-0.355953,-0.988623,-1.026041,-0.965151,...,0.315946,-0.534551,-1.077559,-0.708560,0.781971,-0.892086,1.062205,-0.633365,0.993174,1.062205
522,-1.293411,-0.073068,-0.807338,-1.689368,-0.809621,-0.116276,-0.422167,0.333044,0.789741,0.332382,...,0.315946,-0.244745,0.436516,-0.708560,0.781971,-0.892086,1.062205,-0.633365,0.993174,1.062205
1036,0.904675,2.104067,1.186145,1.120936,0.836436,1.432235,1.277336,0.241607,0.789741,-0.316385,...,1.662750,2.131667,-1.077559,1.411313,-1.278819,1.120968,-0.941438,1.578868,-1.006873,-0.941438

In [31]:
y_train.head()

254     145000.0
1066    178000.0
638      85000.0
799     175000.0
380     127000.0
Name: SalePrice, dtype: float64

In [32]:
y_test.head()

892     154500.0
1105    325000.0
413     115000.0
522     159000.0
1036    315500.0
Name: SalePrice, dtype: float64

In [33]:
models = {
    "Linear Regression": LinearRegression(),

    "Decision Tree": DecisionTreeRegressor(
        random_state=42
    ),

    "Random Forest": RandomForestRegressor(
        random_state=42
    ),

    "Gradient Boosting": GradientBoostingRegressor(
        random_state=42
    ),

    "XGBoost": XGBRegressor(
        random_state=42
    ),

    "LightGBM": LGBMRegressor(
        random_state=42
    ),

    "CatBoost": CatBoostRegressor(
        verbose=0,
        random_state=42
    )
}

In [34]:
results = []

for model_name, model in models.items():

    model.fit( X_train, y_train )

    predictions = model.predict( X_test )

    mae = mean_absolute_error( y_test, predictions )

    mse = mean_squared_error(y_test,predictions)

    r2 = r2_score( y_test, predictions)

    results.append({

        "Model": model_name,

        "MAE": mae,

        "MSE": mse,

        "R2 Score": r2

    })

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000324 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1770
[LightGBM] [Info] Number of data points in the train set: 1168, number of used features: 22
[LightGBM] [Info] Start training from score 178189.621575

In [35]:
results

[{'Model': 'Linear Regression',
  'MAE': 18054.345279722525,
  'MSE': 549055186.0593597,
  'R2 Score': 0.8877015514553102},
 {'Model': 'Decision Tree',
  'MAE': 21249.91609589041,
  'MSE': 932984862.333048,
  'R2 Score': 0.8091762809715906},
 {'Model': 'Random Forest',
  'MAE': 16145.002712818003,
  'MSE': 503692855.82090694,
  'R2 Score': 0.8969795246672768},
 {'Model': 'Gradient Boosting',
  'MAE': 16208.064207084748,
  'MSE': 484359993.125959,
  'R2 Score': 0.9009336818115743},
 {'Model': 'XGBoost',
  'MAE': 17561.296406785103,
  'MSE': 599391245.5429516,
  'R2 Score': 0.8774062996675427},
 {'Model': 'LightGBM',
  'MAE': 15778.887445995559,
  'MSE': 470118588.1602104,
  'R2 Score': 0.9038464813321989},
 {'Model': 'CatBoost',
  'MAE': 15604.898857834443,
  'MSE': 469836481.62865365,
  'R2 Score': 0.9039041806794094}]

In [36]:
results = pd.DataFrame(results)

results.sort_values( by="R2 Score", ascending=False )

               Model           MAE           MSE  R2 Score
6           CatBoost  15604.898858  4.698365e+08  0.903904
5           LightGBM  15778.887446  4.701186e+08  0.903846
3  Gradient Boosting  16208.064207  4.843600e+08  0.900934
2      Random Forest  16145.002713  5.036929e+08  0.896980
0  Linear Regression  18054.345280  5.490552e+08  0.887702
4            XGBoost  17561.296407  5.993912e+08  0.877406
1      Decision Tree  21249.916096  9.329849e+08  0.809176

# Model Training completed