In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import ( RandomForestRegressor,GradientBoostingRegressor )
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

In [2]:
from sklearn.metrics import ( mean_absolute_error, mean_squared_error, r2_score )

In [4]:
train = pd.read_csv("../dataset/cleaned/train_processed.csv")

train.head()

,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtUnfSF,TotalBsmtSF,...,GarageQual_Fa,GarageQual_TA,GarageCond_Fa,GarageCond_TA,PavedDrive_Y,SaleType_New,SaleType_WD,SaleCondition_Normal,SaleCondition_Partial,SalePrice
0,-0.237456,-0.333244,0.652644,-0.564161,1.053246,0.878668,1.224128,0.614224,-0.958790,-0.488321,...,-0.203801,0.290522,-0.170457,0.276034,0.261789,-0.359481,0.329514,0.383663,-0.365276,208500.0
1,0.633321,-0.013189,-0.073068,2.030907,0.156179,-0.429577,-0.813256,1.242296,-0.648290,0.532289,...,-0.203801,0.290522,-0.170457,0.276034,0.261789,-0.359481,0.329514,0.383663,-0.365276,181500.0
2,-0.063300,0.446022,0.652644,-0.564161,0.986797,0.830215,1.151068,0.106224,-0.300716,-0.327437,...,-0.203801,0.290522,-0.170457,0.276034,0.261789,-0.359481,0.329514,0.383663,-0.365276,223500.0
3,-0.527714,-0.027104,0.652644,-0.564161,-1.870528,-0.720298,-0.813256,-0.517230,-0.055097,-0.739702,...,-0.203801,0.290522,-0.170457,0.276034,0.261789,-0.359481,0.329514,NaN,-0.365276,140000.0
4,0.865528,1.283733,1.378355,-0.564161,0.953572,0.733308,1.446863,0.496460,-0.170955,0.238172,...,-0.203801,0.290522,-0.170457,0.276034,0.261789,-0.359481,0.329514,0.383663,-0.365276,250000.0

In [10]:
missing = train.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

missing

RoofStyle_Gable         319
MSZoning_RL             309
SaleCondition_Normal    262
BsmtFinType2_Unf        204
Condition1_Norm         200
SaleType_WD             193
ExterCond_TA            178
GarageQual_TA           149
BsmtCond_TA             149
GarageCond_TA           134
Electrical_SBrkr        126
PavedDrive_Y            120
Functional_Typ          100
CentralAir_Y             95
GarageYrBlt              81
Heating_GasA             32
MasVnrArea                8
dtype: int64

In [11]:
numerical_columns = train.select_dtypes(include=["int64", "float64"]).columns

for column in numerical_columns:
    train[column] = train[column].fillna(train[column].median())

In [12]:
X = train.drop("SalePrice", axis=1)

y = train["SalePrice"]

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [14]:
models = {
    "Linear Regression": LinearRegression(),

    "Decision Tree": DecisionTreeRegressor(
        random_state=42
    ),

    "Random Forest": RandomForestRegressor(
        random_state=42
    ),

    "Gradient Boosting": GradientBoostingRegressor(
        random_state=42
    ),

    "XGBoost": XGBRegressor(
        random_state=42
    ),

    "LightGBM": LGBMRegressor(
        random_state=42
    ),

    "CatBoost": CatBoostRegressor(
        verbose=0,
        random_state=42
    )
}

In [ ]:
results = []

for model_name, model in models.items():

    model.fit( X_train, y_train )

    predictions = model.predict( X_test )

    mae = mean_absolute_error( y_test, predictions )

    rmse = mean_squared_error(y_test,predictions)

    r2 = r2_score( y_test, predictions)

    results.append({

        "Model": model_name,

        "MAE": mae,

        "RMSE": rmse,

        "R2 Score": r2

    })

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005472 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2823
[LightGBM] [Info] Number of data points in the train set: 1168, number of used features: 88
[LightGBM] [Info] Start training from score 178189.621575

In [17]:
results

[{'Model': 'Linear Regression',
  'MAE': 15246.381688291309,
  'RMSE': 424382324.2674987,
  'R2 Score': 0.9132009353247832},
 {'Model': 'Decision Tree',
  'MAE': 23166.179794520547,
  'RMSE': 1065263821.3707192,
  'R2 Score': 0.7821212193817869},
 {'Model': 'Random Forest',
  'MAE': 14841.946883561644,
  'RMSE': 427156357.1985587,
  'R2 Score': 0.912633561402672},
 {'Model': 'Gradient Boosting',
  'MAE': 14621.515285849862,
  'RMSE': 410105913.3240894,
  'R2 Score': 0.916120894630218},
 {'Model': 'XGBoost',
  'MAE': 15419.488562178938,
  'RMSE': 488835950.67788404,
  'R2 Score': 0.9000182126536548},
 {'Model': 'LightGBM',
  'MAE': 14033.540212860751,
  'RMSE': 374029970.5190796,
  'R2 Score': 0.9234995197842141},
 {'Model': 'CatBoost',
  'MAE': 13442.608462000544,
  'RMSE': 358592335.211929,
  'R2 Score': 0.9266569847134394}]

In [18]:
results = pd.DataFrame(results)

results.sort_values( by="R2 Score", ascending=False )

               Model           MAE          RMSE  R2 Score
6           CatBoost  13442.608462  3.585923e+08  0.926657
5           LightGBM  14033.540213  3.740300e+08  0.923500
3  Gradient Boosting  14621.515286  4.101059e+08  0.916121
0  Linear Regression  15246.381688  4.243823e+08  0.913201
2      Random Forest  14841.946884  4.271564e+08  0.912634
4            XGBoost  15419.488562  4.888360e+08  0.900018
1      Decision Tree  23166.179795  1.065264e+09  0.782121