In [1]:
import pandas as pd

In [8]:
# importing pandas as pd
import pandas as pd

# Creating the dataframe 
df = pd.DataFrame({"A":[12, 4, 5, None, 1],
                   "B":[None, 2, 54, 3, None],
                   "C":[20, 16, None, 3, 8],
                   "D":[14, 3, None, None, 6]})
print(df)
# to interpolate the missing values
df.interpolate(method ='linear', limit_direction ='both', inplace = True)
print("\nDataframe after interpolating the missing values:\n", df)

      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   NaN   NaN
3   NaN   3.0   3.0   NaN
4   1.0   NaN   8.0   6.0

Dataframe after interpolating the missing values:
       A     B     C     D
0  12.0   2.0  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   9.5   4.0
3   3.0   3.0   3.0   5.0
4   1.0   3.0   8.0   6.0

In [11]:
df = pd.read_csv("../Dataset/df_for_EDA.csv")

In [12]:
df

,Datetime,PJME_MW,Hour,DayOfWeek,Month,Day,Week,Year,IsWeekend,Lag_1,Lag_24,Lag_168,RollingMean_24,RollingMean_168,RollingStd_24
0,1998-12-24 01:00:00,27213.0,1,3,12,24,52,1998,0,28570.0,27669.0,26498.0,29475.375000,30894.589286,2736.646326
1,1998-12-24 02:00:00,25643.0,2,3,12,24,52,1998,0,27213.0,26162.0,25147.0,29453.750000,30897.541667,2765.861628
2,1998-12-24 03:00:00,24907.0,3,3,12,24,52,1998,0,25643.0,25483.0,24574.0,29429.750000,30899.523810,2804.050165
3,1998-12-24 04:00:00,24721.0,4,3,12,24,52,1998,0,24907.0,25045.0,24393.0,29416.250000,30901.476190,2826.766154
4,1998-12-24 05:00:00,25144.0,5,3,12,24,52,1998,0,24721.0,25030.0,24860.0,29421.000000,30903.166667,2819.160745
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145193,2014-03-02 03:00:00,44284.0,3,6,3,2,9,2014,1,44343.0,45787.0,42112.0,40343.500000,41856.327381,2295.270146
145194,2014-03-02 04:00:00,43751.0,4,6,3,2,9,2014,1,44284.0,45209.0,40797.0,40282.750000,41873.910714,2177.148998
145195,2014-03-02 05:00:00,42402.0,5,6,3,2,9,2014,1,43751.0,43663.0,38819.0,40230.208333,41895.238095,2106.081917
145196,2014-03-02 06:00:00,40164.0,6,6,3,2,9,2014,1,42402.0,41581.0,36287.0,40171.166667,41918.315476,2086.336995
145197,2014-03-02 07:00:00,38608.0,7,6,3,2,9,2014,1,40164.0,39451.0,34077.0,40136.041667,41945.285714,2105.992351

In [14]:
df = df.set_index("Datetime")

In [15]:
df

,PJME_MW,Hour,DayOfWeek,Month,Day,Week,Year,IsWeekend,Lag_1,Lag_24,Lag_168,RollingMean_24,RollingMean_168,RollingStd_24
Datetime,,,,,,,,,,,,,,
1998-12-24 01:00:00,27213.0,1,3,12,24,52,1998,0,28570.0,27669.0,26498.0,29475.375000,30894.589286,2736.646326
1998-12-24 02:00:00,25643.0,2,3,12,24,52,1998,0,27213.0,26162.0,25147.0,29453.750000,30897.541667,2765.861628
1998-12-24 03:00:00,24907.0,3,3,12,24,52,1998,0,25643.0,25483.0,24574.0,29429.750000,30899.523810,2804.050165
1998-12-24 04:00:00,24721.0,4,3,12,24,52,1998,0,24907.0,25045.0,24393.0,29416.250000,30901.476190,2826.766154
1998-12-24 05:00:00,25144.0,5,3,12,24,52,1998,0,24721.0,25030.0,24860.0,29421.000000,30903.166667,2819.160745
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-03-02 03:00:00,44284.0,3,6,3,2,9,2014,1,44343.0,45787.0,42112.0,40343.500000,41856.327381,2295.270146
2014-03-02 04:00:00,43751.0,4,6,3,2,9,2014,1,44284.0,45209.0,40797.0,40282.750000,41873.910714,2177.148998
2014-03-02 05:00:00,42402.0,5,6,3,2,9,2014,1,43751.0,43663.0,38819.0,40230.208333,41895.238095,2106.081917
2014-03-02 06:00:00,40164.0,6,6,3,2,9,2014,1,42402.0,41581.0,36287.0,40171.166667,41918.315476,2086.336995
2014-03-02 07:00:00,38608.0,7,6,3,2,9,2014,1,40164.0,39451.0,34077.0,40136.041667,41945.285714,2105.992351

In [21]:
df.index

Index(['1998-12-24 01:00:00', '1998-12-24 02:00:00', '1998-12-24 03:00:00',
       '1998-12-24 04:00:00', '1998-12-24 05:00:00', '1998-12-24 06:00:00',
       '1998-12-24 07:00:00', '1998-12-24 08:00:00', '1998-12-24 09:00:00',
       '1998-12-24 10:00:00',
       ...
       '2014-03-03 22:00:00', '2014-03-03 23:00:00', '2014-03-04 00:00:00',
       '2014-03-02 01:00:00', '2014-03-02 02:00:00', '2014-03-02 03:00:00',
       '2014-03-02 04:00:00', '2014-03-02 05:00:00', '2014-03-02 06:00:00',
       '2014-03-02 07:00:00'],
      dtype='str', name='Datetime', length=145198)

In [22]:
df.index = pd.to_datetime(df.index)

In [23]:
df.index.dtype

dtype('<M8[us]')

In [24]:
quarter = df.index.quarter

In [25]:
quarter

Index([4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       ...
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype='int32', name='Datetime', length=145198)